name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/my-pipeline:latest

  run-pipeline:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull your-dockerhub-username/my-pipeline:latest
          docker run --rm your-dockerhub-username/my-pipeline
